# Generated by Django 5.1 on 2026-03-29 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("website", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GrantingAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("abbreviation", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name_plural": "Granting agencies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "short_code",
                    models.CharField(
                        help_text="e.g. 'MTL', 'LEI', 'COR', 'UBC'",
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CellLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "genotype",
                    models.CharField(
                        choices=[
                            ("WT", "Wild Type"),
                            ("KO", "Knockout"),
                            ("other", "Other"),
                        ],
                        default="WT",
                        max_length=10,
                    ),
                ),
                ("catalogue_number", models.CharField(blank=True, max_length=255)),
                ("lot_number", models.CharField(blank=True, max_length=255)),
                (
                    "cellosaurus_id",
                    models.CharField(
                        blank=True,
                        help_text="Cellosaurus RRID, e.g. CVCL_0030",
                        max_length=100,
                    ),
                ),
                (
                    "species",
                    models.CharField(blank=True, default="Human", max_length=100),
                ),
                ("origin", models.CharField(blank=True, max_length=255)),
                (
                    "in_kind_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="In-kind contribution value (currency per site)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "in_kind_currency",
                    models.CharField(
                        blank=True,
                        default="GBP",
                        help_text="ISO currency code",
                        max_length=3,
                    ),
                ),
                ("received", models.BooleanField(default=False)),
                (
                    "ko_validated",
                    models.BooleanField(
                        default=False,
                        help_text="Has this KO been validated by WB (no truncated protein)?",
                    ),
                ),
                ("ko_validation_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("access_id", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "parent_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="For KO lines, the WT parent cell line",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ko_derivatives",
                        to="pipeline.cellline",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cell_lines",
                        to="pipeline.company",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cell_lines",
                        to="pipeline.site",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Antibody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ab_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Internal sequential antibody number (Access legacy)",
                        null=True,
                    ),
                ),
                ("catalogue_number", models.CharField(blank=True, max_length=255)),
                ("lot_number", models.CharField(blank=True, max_length=255)),
                (
                    "rrid",
                    models.CharField(
                        blank=True,
                        help_text="Research Resource Identifier, e.g. AB_10677043",
                        max_length=255,
                    ),
                ),
                (
                    "clonality",
                    models.CharField(
                        choices=[
                            ("monoclonal", "Monoclonal"),
                            ("polyclonal", "Polyclonal"),
                            ("recombinant", "Recombinant"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("clone_id", models.CharField(blank=True, max_length=255)),
                (
                    "host_species",
                    models.CharField(
                        blank=True,
                        help_text="Host expression system / species",
                        max_length=255,
                    ),
                ),
                (
                    "concentration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Concentration in µg/mL",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("isotype", models.CharField(blank=True, max_length=100)),
                ("species_reactivity", models.CharField(blank=True, max_length=255)),
                ("is_recombinant", models.BooleanField(default=False)),
                ("supplier_validated_wb", models.BooleanField(default=False)),
                ("supplier_validated_ip", models.BooleanField(default=False)),
                ("supplier_validated_if", models.BooleanField(default=False)),
                ("supplier_validated_ihc", models.BooleanField(default=False)),
                ("supplier_validated_elisa", models.BooleanField(default=False)),
                ("supplier_validated_fc", models.BooleanField(default=False)),
                (
                    "supplier_validated_applications",
                    models.CharField(blank=True, max_length=500),
                ),
                ("validation_details_wb", models.TextField(blank=True)),
                ("validation_details_if", models.TextField(blank=True)),
                (
                    "acquisition_method",
                    models.CharField(
                        choices=[
                            ("purchased", "Purchased"),
                            ("in_kind", "In Kind"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("received_date", models.DateField(blank=True, null=True)),
                (
                    "in_kind_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "in_kind_currency",
                    models.CharField(blank=True, default="GBP", max_length=3),
                ),
                (
                    "out_of_market",
                    models.BooleanField(
                        default=False, help_text="No longer commercially available"
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("access_id", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="antibodies",
                        to="pipeline.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Antibodies",
                "ordering": ["target", "company", "catalogue_number"],
            },
        ),
        migrations.CreateModel(
            name="ExperimentSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "procedure_type",
                    models.CharField(
                        choices=[
                            ("WB", "Western Blot"),
                            ("IP", "Immunoprecipitation"),
                            ("IF", "Immunofluorescence"),
                            ("FC", "Flow Cytometry"),
                        ],
                        max_length=2,
                    ),
                ),
                ("date", models.DateField(help_text="Date experiment was performed")),
                (
                    "session_conditions",
                    models.JSONField(
                        default=dict,
                        help_text="Session-level experimental conditions (supplements/overrides template)",
                    ),
                ),
                (
                    "fc_sub_protocol",
                    models.CharField(
                        choices=[
                            ("ic_saponin", "Intracellular PFA/Saponin"),
                            ("ic_triton", "Intracellular PFA/Triton"),
                            ("surface", "Cell Surface"),
                            ("na", "N/A"),
                        ],
                        default="na",
                        help_text="Only applicable for FC sessions",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                            ("repeat_needed", "Repeat Needed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cell_line_ko",
                    models.ForeignKey(
                        blank=True,
                        help_text="Knockout cell line",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_as_ko",
                        to="pipeline.cellline",
                    ),
                ),
                (
                    "cell_line_wt",
                    models.ForeignKey(
                        blank=True,
                        help_text="Wild-type cell line",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_as_wt",
                        to="pipeline.cellline",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "target"],
            },
        ),
        migrations.CreateModel(
            name="FcResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("concentration", models.CharField(blank=True, max_length=100)),
                (
                    "histogram_shift",
                    models.CharField(
                        blank=True,
                        help_text="Assessment of WT vs KO separation in histogram",
                        max_length=255,
                    ),
                ),
                (
                    "median_fluorescence_wt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "median_fluorescence_ko",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("gating_strategy", models.TextField(blank=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fc_results",
                        to="pipeline.antibody",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fc_results",
                        to="pipeline.experimentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "FC result",
                "verbose_name_plural": "FC results",
            },
        ),
        migrations.CreateModel(
            name="IfResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_signal", models.CharField(blank=True, max_length=255)),
                (
                    "wt_ko_ratio_1",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "wt_ko_ratio_2",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("concentration_1", models.CharField(blank=True, max_length=100)),
                ("concentration_2", models.CharField(blank=True, max_length=100)),
                ("best_concentration", models.CharField(blank=True, max_length=100)),
                ("fixative", models.CharField(blank=True, max_length=255)),
                ("blocking", models.CharField(blank=True, max_length=255)),
                ("permeabilisation", models.CharField(blank=True, max_length=255)),
                ("primary_ab_dilution", models.CharField(blank=True, max_length=255)),
                ("dilution_buffer", models.CharField(blank=True, max_length=255)),
                ("primary_ab_condition", models.CharField(blank=True, max_length=255)),
                ("secondary_ab", models.CharField(blank=True, max_length=255)),
                (
                    "secondary_ab_condition",
                    models.CharField(blank=True, max_length=255),
                ),
                ("plate_number", models.CharField(blank=True, max_length=50)),
                ("well_number", models.CharField(blank=True, max_length=50)),
                ("image_acquired_by", models.CharField(blank=True, max_length=255)),
                ("image_analysed_by", models.CharField(blank=True, max_length=255)),
                ("microscope", models.CharField(blank=True, max_length=255)),
                ("objective", models.CharField(blank=True, max_length=255)),
                ("comments", models.TextField(blank=True)),
                ("access_id", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="if_results",
                        to="pipeline.antibody",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="if_results",
                        to="pipeline.experimentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "IF result",
                "verbose_name_plural": "IF results",
            },
        ),
        migrations.CreateModel(
            name="IpResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrichment", models.CharField(blank=True, max_length=255)),
                ("amount_of_antibody", models.CharField(blank=True, max_length=255)),
                ("amount_of_lysate", models.CharField(blank=True, max_length=255)),
                ("protein_concentration", models.CharField(blank=True, max_length=255)),
                ("volume_of_lysate_ml", models.CharField(blank=True, max_length=255)),
                ("bead_type", models.CharField(blank=True, max_length=255)),
                ("lysis_buffer", models.CharField(blank=True, max_length=255)),
                (
                    "detection_ab",
                    models.CharField(
                        blank=True,
                        help_text="KO-validated antibody used for WB detection step",
                        max_length=255,
                    ),
                ),
                ("detection_ab_dilution", models.CharField(blank=True, max_length=255)),
                ("secondary_ab", models.CharField(blank=True, max_length=255)),
                ("secondary_ab_dilution", models.CharField(blank=True, max_length=255)),
                ("gel", models.CharField(blank=True, max_length=255)),
                ("membrane", models.CharField(blank=True, max_length=255)),
                ("ecl", models.CharField(blank=True, max_length=255)),
                ("detection_system", models.CharField(blank=True, max_length=255)),
                ("sm_assessment", models.CharField(blank=True, max_length=255)),
                ("ub_assessment", models.CharField(blank=True, max_length=255)),
                ("ip_assessment", models.CharField(blank=True, max_length=255)),
                ("comments", models.TextField(blank=True)),
                ("access_id", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_results",
                        to="pipeline.antibody",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ip_results",
                        to="pipeline.experimentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP result",
                "verbose_name_plural": "IP results",
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("pi", "Principal Investigator"),
                            ("coordinator", "Logistics Coordinator"),
                            ("experimenter", "Experimenter"),
                            ("viewer", "View Only"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional override for display; otherwise uses User names",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_member",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="pipeline.site",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experimentsession",
            name="experimenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="pipeline.member",
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="antibodies_created",
                to="pipeline.member",
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "granting_agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="pipeline.grantingagency",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. 'Leicester WB standard', 'Montreal IF standard'",
                        max_length=255,
                    ),
                ),
                (
                    "procedure_type",
                    models.CharField(
                        choices=[
                            ("WB", "Western Blot"),
                            ("IP", "Immunoprecipitation"),
                            ("IF", "Immunofluorescence"),
                            ("FC", "Flow Cytometry"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Default template for this site + procedure combination",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict, help_text="Structured protocol conditions as JSON"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pipeline.member",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protocol_templates",
                        to="pipeline.site",
                    ),
                ),
            ],
            options={
                "ordering": ["site", "procedure_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="experimentsession",
            name="protocol_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="pipeline.protocoltemplate",
            ),
        ),
        migrations.CreateModel(
            name="ReagentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("antibody", "Antibody"), ("cell_line", "Cell Line")],
                        max_length=20,
                    ),
                ),
                ("catalogue_number", models.CharField(blank=True, max_length=255)),
                ("rrid", models.CharField(blank=True, max_length=255)),
                ("expected_clonality", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("shipped", "Shipped"),
                            ("received", "Received"),
                            ("partial", "Partially Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("requested_date", models.DateField(blank=True, null=True)),
                ("shipped_date", models.DateField(blank=True, null=True)),
                ("received_date", models.DateField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked after receipt confirmation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reagent_request",
                        to="pipeline.antibody",
                    ),
                ),
                (
                    "cell_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked after receipt confirmation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reagent_request",
                        to="pipeline.cellline",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reagent_requests",
                        to="pipeline.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reagent_requests",
                        to="pipeline.project",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reagent_requests",
                        to="pipeline.member",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reagent_requests",
                        to="pipeline.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_date", models.DateField()),
                ("tracking_number", models.CharField(blank=True, max_length=255)),
                (
                    "condition_notes",
                    models.TextField(
                        blank=True,
                        help_text="Condition on arrival, temperature, packaging",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="pipeline.company",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments_received",
                        to="pipeline.member",
                    ),
                ),
                (
                    "requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shipments",
                        to="pipeline.reagentrequest",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="pipeline.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("4c", "4°C Fridge"),
                            ("-20", "-20°C Freezer"),
                            ("-80", "-80°C Freezer"),
                            ("ln2", "Liquid Nitrogen"),
                            ("rt", "Room Temperature"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("building", models.CharField(blank=True, max_length=100)),
                ("room", models.CharField(blank=True, max_length=100)),
                ("freezer", models.CharField(blank=True, max_length=100)),
                ("shelf", models.CharField(blank=True, max_length=100)),
                ("rack", models.CharField(blank=True, max_length=100)),
                ("box", models.CharField(blank=True, max_length=100)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="pipeline.antibody",
                    ),
                ),
                (
                    "cell_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="pipeline.cellline",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pipeline.site"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventory locations",
            },
        ),
        migrations.AddField(
            model_name="experimentsession",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="pipeline.site",
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="antibodies",
                to="pipeline.site",
            ),
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protein_name", models.CharField(max_length=255)),
                ("gene_name", models.CharField(blank=True, max_length=255)),
                ("alternative_name", models.CharField(blank=True, max_length=255)),
                (
                    "uniprot_id",
                    models.CharField(
                        blank=True,
                        help_text="UniProt accession, e.g. P37840",
                        max_length=50,
                    ),
                ),
                (
                    "theoretical_mass_kda",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Predicted molecular weight in kDa",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("protein_type", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("wb_complete", "WB Complete"),
                            ("ip_complete", "IP Complete"),
                            ("if_complete", "IF Complete"),
                            ("fc_complete", "FC Complete"),
                            ("report_ready", "Report Ready"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                            ("on_hold", "On Hold"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("commercial_ko_available", models.BooleanField(default=False)),
                ("ko_validated", models.BooleanField(default=False)),
                (
                    "depmap_expression",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="log2(TPM+1) from DepMap; threshold ≥2.5 for suitability",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "access_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Original Proteins.ID from Access DB for migration reference",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targets_created",
                        to="pipeline.member",
                    ),
                ),
                (
                    "granting_agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targets",
                        to="pipeline.grantingagency",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targets",
                        to="pipeline.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="targets",
                        to="pipeline.site",
                    ),
                ),
            ],
            options={
                "ordering": ["protein_name"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generated", "Generated"),
                            ("submitted", "Submitted"),
                            ("published", "Published"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "zenodo_doi",
                    models.URLField(blank=True, help_text="Zenodo DOI link"),
                ),
                (
                    "f1000_doi",
                    models.URLField(blank=True, help_text="F1000Research DOI link"),
                ),
                ("zenodo_date", models.DateField(blank=True, null=True)),
                ("f1000_date", models.DateField(blank=True, null=True)),
                (
                    "introduction_text",
                    models.TextField(
                        blank=True,
                        help_text="Manually written disease context paragraph",
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pipeline.member",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="pipeline.target",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reagent_requests",
                to="pipeline.target",
            ),
        ),
        migrations.AddField(
            model_name="experimentsession",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="pipeline.target",
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cell_lines",
                to="pipeline.target",
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="antibodies",
                to="pipeline.target",
            ),
        ),
        migrations.CreateModel(
            name="WbResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dilution", models.CharField(blank=True, max_length=100)),
                ("exposure_time", models.CharField(blank=True, max_length=100)),
                (
                    "signal",
                    models.CharField(
                        blank=True,
                        help_text="Band pattern / signal assessment",
                        max_length=255,
                    ),
                ),
                ("rating", models.CharField(blank=True, max_length=100)),
                (
                    "extra_lanes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional cell line lanes beyond WT/KO, as list of {cell_line_id, label}",
                    ),
                ),
                ("gel", models.CharField(blank=True, max_length=255)),
                ("membrane", models.CharField(blank=True, max_length=255)),
                ("ecl", models.CharField(blank=True, max_length=255)),
                ("detection_system", models.CharField(blank=True, max_length=255)),
                ("primary_ab_dilution", models.CharField(blank=True, max_length=255)),
                ("secondary_ab", models.CharField(blank=True, max_length=255)),
                ("secondary_ab_dilution", models.CharField(blank=True, max_length=255)),
                ("comments", models.TextField(blank=True)),
                ("access_id", models.IntegerField(blank=True, null=True, unique=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wb_results",
                        to="pipeline.antibody",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wb_results",
                        to="pipeline.experimentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "WB result",
                "verbose_name_plural": "WB results",
            },
        ),
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wb_scan", "WB Scan"),
                            ("wb_composite", "WB Composite Panel"),
                            ("ponceau", "Ponceau S Stain"),
                            ("if_image", "IF Image"),
                            ("if_plate", "IF Plate Overview"),
                            ("fc_histogram", "FC Histogram"),
                            ("fc_fcs", "FC Raw Data (.fcs)"),
                            ("ip_scan", "IP Scan"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="pipeline/attachments/%Y/%m/")),
                ("original_filename", models.CharField(max_length=500)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fc_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="pipeline.fcresult",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="pipeline.experimentsession",
                    ),
                ),
                (
                    "if_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="pipeline.ifresult",
                    ),
                ),
                (
                    "ip_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="pipeline.ipresult",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pipeline.member",
                    ),
                ),
                (
                    "wb_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="pipeline.wbresult",
                    ),
                ),
            ],
        ),
    ]
