# Generated by Django 5.1 on 2026-03-29 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("WB", "Western Blot"),
                            ("IP", "Immunoprecipitation"),
                            ("IF", "Immunofluorescence"),
                            ("FC", "Flow Cytometry"),
                            ("KO", "KO Cell Line Generation"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("blocked", "Blocked"),
                            ("na", "Not Applicable"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("assigned_date", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Higher number = higher priority"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="E.g. 'FC only per MJFF agreement', 'KO clone failed, retrying'",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["target", "site", "task_type"],
            },
        ),
        migrations.AlterField(
            model_name="target",
            name="gene_name",
            field=models.CharField(
                blank=True,
                help_text="Gene symbol — unique across all sites to prevent duplicate work",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Site that initiated this target — not exclusive ownership",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="targets",
                to="pipeline.site",
            ),
        ),
        migrations.AlterField(
            model_name="target",
            name="uniprot_id",
            field=models.CharField(
                blank=True,
                help_text="UniProt accession, e.g. P37840 — unique across all sites",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="antibody",
            constraint=models.UniqueConstraint(
                fields=("catalogue_number", "company", "target"),
                name="unique_antibody_per_target",
            ),
        ),
        migrations.AddField(
            model_name="targetassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments_made",
                to="pipeline.member",
            ),
        ),
        migrations.AddField(
            model_name="targetassignment",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments_received",
                to="pipeline.member",
            ),
        ),
        migrations.AddField(
            model_name="targetassignment",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="pipeline.site",
            ),
        ),
        migrations.AddField(
            model_name="targetassignment",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="pipeline.target",
            ),
        ),
        migrations.AddConstraint(
            model_name="targetassignment",
            constraint=models.UniqueConstraint(
                fields=("target", "site", "task_type"),
                name="unique_assignment_per_site_task",
            ),
        ),
    ]
