# Generated by Django 5.1 on 2026-03-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_targetassignment_alter_target_gene_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="antibody",
            name="unique_antibody_per_target",
        ),
        migrations.AddConstraint(
            model_name="antibody",
            constraint=models.UniqueConstraint(
                fields=("catalogue_number", "company", "target", "lot_number", "site"),
                name="unique_antibody_per_site_lot",
            ),
        ),
    ]
