# Generated by Django 5.1 on 2026-04-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0003_remove_antibody_unique_antibody_per_target_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepMapExpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gene_name",
                    models.CharField(
                        db_index=True,
                        help_text="HUGO gene symbol, e.g. 'SYT1'",
                        max_length=50,
                    ),
                ),
                (
                    "entrez_id",
                    models.IntegerField(
                        blank=True,
                        help_text="NCBI Entrez Gene ID, e.g. 6857",
                        null=True,
                    ),
                ),
                (
                    "cell_line",
                    models.CharField(
                        db_index=True,
                        help_text="Cell line name, e.g. 'HAP1', 'HCT116'",
                        max_length=100,
                    ),
                ),
                (
                    "depmap_id",
                    models.CharField(
                        blank=True,
                        help_text="DepMap model ID, e.g. 'ACH-001234'",
                        max_length=30,
                    ),
                ),
                (
                    "tpm_log2",
                    models.FloatField(
                        help_text="Expression value as log2(TPM+1). Threshold ≥2.5 for YCharOS."
                    ),
                ),
                (
                    "depmap_release",
                    models.CharField(
                        blank=True,
                        help_text="DepMap release version, e.g. '25Q2'",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["gene_name", "cell_line"],
                "indexes": [
                    models.Index(
                        fields=["gene_name", "cell_line"],
                        name="pipeline_de_gene_na_f6e0e4_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gene_name", "cell_line"),
                        name="unique_depmap_gene_cellline",
                    )
                ],
            },
        ),
    ]
