# Generated by Django 5.1 on 2026-04-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0004_depmapexpression"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProteomicsExpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gene_name",
                    models.CharField(
                        db_index=True,
                        help_text="HUGO gene symbol, e.g. 'SYT1'",
                        max_length=50,
                    ),
                ),
                (
                    "uniprot_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="UniProt accession, e.g. 'P21579'",
                        max_length=20,
                    ),
                ),
                (
                    "cell_line",
                    models.CharField(
                        db_index=True,
                        help_text="Cell line name, e.g. 'HCT-116'",
                        max_length=100,
                    ),
                ),
                (
                    "protein_intensity",
                    models.FloatField(help_text="Log2 protein intensity from DIA-MS"),
                ),
                (
                    "dataset_version",
                    models.CharField(
                        blank=True,
                        help_text="Dataset version date, e.g. '20250211'",
                        max_length=30,
                    ),
                ),
            ],
            options={
                "ordering": ["gene_name", "cell_line"],
                "indexes": [
                    models.Index(
                        fields=["gene_name", "cell_line"],
                        name="pipeline_pr_gene_na_49a6c3_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("gene_name", "uniprot_id", "cell_line"),
                        name="unique_proteomics_gene_cellline",
                    )
                ],
            },
        ),
    ]
