# Generated by Django 5.1 on 2026-04-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0005_proteomicsexpression"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depmapexpression",
            name="gene_name",
            field=models.CharField(
                db_index=True, help_text="HUGO gene symbol, e.g. 'SYT1'", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="proteomicsexpression",
            name="gene_name",
            field=models.CharField(
                db_index=True, help_text="HUGO gene symbol, e.g. 'SYT1'", max_length=100
            ),
        ),
    ]
