# Generated by Django 5.1 on 2026-04-03 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0006_alter_depmapexpression_gene_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="antibody",
            name="antigen",
            field=models.CharField(
                blank=True, help_text="Immunogen / antigen", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="empty_vial",
            field=models.BooleanField(
                default=False, help_text="Vial is empty / used up"
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="is_test",
            field=models.BooleanField(
                default=False, help_text="Test/trial antibody flag"
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="others_flag",
            field=models.BooleanField(
                default=False, help_text="Miscellaneous flag from Access"
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="rrid_link",
            field=models.URLField(blank=True, help_text="Link to RRID registry entry"),
        ),
        migrations.AddField(
            model_name="antibody",
            name="supplier_url",
            field=models.URLField(
                blank=True, help_text="Supplier product page URL", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="validated_apps_by_supplier",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="cellline",
            name="acquisition_method",
            field=models.CharField(
                choices=[
                    ("purchased", "Purchased"),
                    ("in_kind", "In Kind"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="arrived_with_ko",
            field=models.ForeignKey(
                blank=True,
                help_text="For WT lines, the KO line it was shipped alongside",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="arrived_with_wt",
                to="pipeline.cellline",
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="c_number",
            field=models.IntegerField(
                blank=True, help_text="Internal lab label / C number", null=True
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="clone",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cellline",
            name="growth_properties",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cellline",
            name="location_original_vial",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cellline",
            name="medium",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cellline",
            name="origin_comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cellline",
            name="parental_line_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="cellline",
            name="received_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cellline",
            name="thawed",
            field=models.BooleanField(
                default=False,
                help_text="Has been thawed? (superseded by CellCultureEvent)",
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="comments_custom_ko",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="target",
            name="date_of_nomination",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="target",
            name="expecting_ab_from",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="target",
            name="funding_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="target",
            name="project_comment",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="target",
            name="request_custom_ko",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="target",
            name="requested_ab_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="target",
            name="requested_commercial_ko",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="target",
            name="shared_in_crac",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="depmapexpression",
            name="cell_line",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="depmapexpression",
            name="depmap_id",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="depmapexpression",
            name="depmap_release",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="depmapexpression",
            name="entrez_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="depmapexpression",
            name="gene_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="depmapexpression",
            name="tpm_log2",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="proteomicsexpression",
            name="cell_line",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="proteomicsexpression",
            name="dataset_version",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="proteomicsexpression",
            name="gene_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="proteomicsexpression",
            name="protein_intensity",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="proteomicsexpression",
            name="uniprot_id",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="targetassignment",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="targetassignment",
            name="priority",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="CellCultureEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("thaw", "Thaw from Storage"),
                            ("passage", "Passage / Split"),
                            ("freeze_down", "Freeze Down"),
                            ("discard", "Discard"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("passage_number", models.IntegerField(blank=True, null=True)),
                ("split_ratio", models.CharField(blank=True, max_length=20)),
                (
                    "vials_frozen",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of vials frozen (freeze_down events)",
                        null=True,
                    ),
                ),
                ("discard_reason", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cell_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="culture_events",
                        to="pipeline.cellline",
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thaw_events",
                        to="pipeline.inventorylocation",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="culture_events",
                        to="pipeline.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cell culture event",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
