# Generated by Django 5.1 on 2026-04-18 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0007_antibody_antigen_antibody_empty_vial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="antibody",
            name="fc_recommended",
            field=models.BooleanField(
                default=False, help_text="Recommended for Flow Cytometry"
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="if_recommended",
            field=models.BooleanField(
                default=False, help_text="Recommended for Immunofluorescence"
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="ip_recommended",
            field=models.BooleanField(
                default=False, help_text="Recommended for Immunoprecipitation"
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="wb_recommended",
            field=models.BooleanField(
                default=False, help_text="Recommended for Western Blot"
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="aliases",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated alternative gene names/symbols (from HGNC)",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="cell_line_link",
            field=models.URLField(
                blank=True,
                help_text="Link to cell line used for this gene's experiments",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="citation",
            field=models.TextField(
                blank=True, help_text="Citation text for this target's publication"
            ),
        ),
        migrations.CreateModel(
            name="PublicationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("WB", "Western Blot"),
                            ("IP", "Immunoprecipitation"),
                            ("ICC-IF", "Immunocytochemistry/IF"),
                            ("FC", "Flow Cytometry"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        help_text="Cropped image for public display (supports SVG, PNG, JPG)",
                        upload_to="publication_images/%Y/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_images",
                        to="pipeline.antibody",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication image",
                "verbose_name_plural": "Publication images",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("antibody", "application_type"),
                        name="unique_pub_image_per_antibody_app",
                    )
                ],
            },
        ),
    ]
