# Generated by Django 5.1 on 2026-04-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0008_antibody_fc_recommended_antibody_if_recommended_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="OGA canonical supplier name for public display (falls back to name if empty)",
                max_length=255,
            ),
        ),
    ]
