# Generated by Django 5.1 on 2026-04-18 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0009_company_display_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CellLineVial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "c_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Internal lab label / C number — one per freeze-down batch",
                        null=True,
                    ),
                ),
                (
                    "freeze_date",
                    models.DateField(
                        blank=True,
                        help_text="Date this batch was frozen down",
                        null=True,
                    ),
                ),
                (
                    "passage_number",
                    models.IntegerField(
                        blank=True,
                        help_text="Passage number at time of freeze-down",
                        null=True,
                    ),
                ),
                (
                    "vial_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of vials created in this freeze-down batch",
                        null=True,
                    ),
                ),
                ("received_date", models.DateField(blank=True, null=True)),
                (
                    "acquisition_method",
                    models.CharField(
                        choices=[
                            ("purchased", "Purchased"),
                            ("in_kind", "In Kind"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                ("received", models.BooleanField(default=False)),
                (
                    "thawed",
                    models.BooleanField(
                        default=False,
                        help_text="Has any vial from this batch been thawed?",
                    ),
                ),
                (
                    "location_original_vial",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "in_kind_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="In-kind contribution value (currency per site)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "in_kind_currency",
                    models.CharField(
                        blank=True,
                        default="GBP",
                        help_text="ISO currency code",
                        max_length=3,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "access_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Original CellLines.ID from Access DB",
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cell_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vials",
                        to="pipeline.cellline",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cell_line_vials",
                        to="pipeline.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cell line vial batch",
                "verbose_name_plural": "Cell line vial batches",
                "ordering": ["cell_line", "c_number"],
            },
        ),
    ]
