# Generated by Django 5.1 on 2026-04-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0010_celllinevial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorylocation",
            name="vial",
            field=models.ForeignKey(
                blank=True,
                help_text="Vial batch this storage location belongs to (replaces direct cell_line FK)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to="pipeline.celllinevial",
            ),
        ),
    ]
