# Generated by Django 5.1 on 2026-04-19 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0011_inventorylocation_vial"),
    ]

    operations = [
        migrations.AddField(
            model_name="antibody",
            name="supplier_recommended_dilutions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per-application recommended dilutions from supplier datasheet. Format: {"WB": "1/1000", "IF": "1/200", "IP": "2 µg", "FC": "1/100"}',
            ),
        ),
        migrations.AddField(
            model_name="experimentsession",
            name="planned_date",
            field=models.DateField(
                blank=True,
                help_text="Date session was planned/created (auto from today)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="experimentsession",
            name="protein_loading_ug",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="µg of protein loaded per lane (for figure legend)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ipresult",
            name="ecl_type",
            field=models.CharField(
                blank=True,
                help_text="e.g. Pierce ECL, Clarity — needed for Zenodo filename",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="ipresult",
            name="exposure_time",
            field=models.CharField(
                blank=True,
                help_text="e.g. 20 mins — needed for Zenodo filename convention",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="protocoltemplate",
            name="protocol_guidance",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Collapsible protocol phases for bench display. List of {title, summary, detail, data_fields} dicts.",
            ),
        ),
        migrations.AlterField(
            model_name="experimentsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in_progress", "In Progress"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("repeat_needed", "Repeat Needed"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ifresult",
            name="permeabilisation",
            field=models.CharField(
                blank=True,
                help_text="e.g. Triton, Saponin — allows 2 IfResult rows per antibody",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sample_type",
                    models.CharField(
                        choices=[
                            ("lysate", "Cell Lysate"),
                            ("supernatant", "Concentrated Supernatant"),
                            ("media", "Culture Medium (unconcentrated)"),
                        ],
                        help_text="Lysate (intracellular) or supernatant (secreted)",
                        max_length=20,
                    ),
                ),
                (
                    "preparation_date",
                    models.DateField(help_text="Date sample was prepared"),
                ),
                (
                    "lysis_buffer",
                    models.CharField(
                        blank=True,
                        help_text="e.g. RIPA, Pierce IP buffer",
                        max_length=200,
                    ),
                ),
                (
                    "protease_inhibitor",
                    models.CharField(
                        blank=True,
                        default="1x protease inhibitor cocktail",
                        help_text="e.g. 1x protease inhibitor cocktail",
                        max_length=200,
                    ),
                ),
                (
                    "protein_concentration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="µg/mL from BCA or Bradford assay",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "quantification_method",
                    models.CharField(
                        blank=True, help_text="e.g. BCA, Bradford", max_length=100
                    ),
                ),
                (
                    "conditioning_time_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Hours of serum-free conditioning (supernatants only)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "concentration_method",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 3 kDa Amicon Ultra, 10 kDa cutoff",
                        max_length=200,
                    ),
                ),
                (
                    "concentration_fold",
                    models.IntegerField(
                        blank=True,
                        help_text="Approximate fold concentration achieved",
                        null=True,
                    ),
                ),
                (
                    "volume_remaining_ul",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Remaining volume in µL",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "storage_location",
                    models.CharField(
                        blank=True,
                        help_text="e.g. -80°C Freezer 2, Rack A",
                        max_length=200,
                    ),
                ),
                (
                    "storage_temperature",
                    models.CharField(
                        blank=True,
                        default="-80°C",
                        help_text="Storage temperature",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("low", "Low Volume"),
                            ("depleted", "Depleted"),
                            ("discarded", "Discarded"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cell_line",
                    models.ForeignKey(
                        help_text="Which cell line this sample was prepared from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="pipeline.cellline",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Auto-populated from logged-in user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_samples",
                        to="pipeline.member",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="pipeline.site",
                    ),
                ),
            ],
            options={
                "ordering": ["-preparation_date"],
            },
        ),
        migrations.AddField(
            model_name="experimentsession",
            name="samples",
            field=models.ManyToManyField(
                blank=True,
                help_text="Lysates/supernatants used in this session",
                related_name="sessions",
                to="pipeline.sample",
            ),
        ),
    ]
