# Generated by Django 5.1 on 2026-04-20 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0013_experimentsession_cancelled_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reagentrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="expected_clonality",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="rrid",
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Number of vials (2 when both sites need the same antibody)",
            ),
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reagent_receipts",
                to="pipeline.member",
            ),
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="received_catalogue_number",
            field=models.CharField(
                blank=True,
                help_text="Actual catalogue number if different from requested",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="received_clonality",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="received_clone_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="received_concentration",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Actual concentration in µg/mL",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="received_host",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="received_isotype",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="received_lot_number",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="received_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="received_quantity",
            field=models.PositiveIntegerField(
                blank=True, help_text="Actual number of vials received", null=True
            ),
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="received_storage_location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="requested_volume_ul",
            field=models.PositiveIntegerField(
                default=100, help_text="Requested volume in µL per vial"
            ),
        ),
        migrations.AlterField(
            model_name="experimentsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("planned", "Planned"),
                    ("in_progress", "In Progress"),
                    ("complete", "Complete"),
                    ("failed", "Failed"),
                    ("repeat_needed", "Repeat Needed"),
                    ("cancelled", "Cancelled"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reagentrequest",
            name="antibody",
            field=models.ForeignKey(
                blank=True,
                help_text="Antibody record created/matched on receipt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reagent_request",
                to="pipeline.antibody",
            ),
        ),
        migrations.AlterField(
            model_name="reagentrequest",
            name="catalogue_number",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reagentrequest",
            name="cell_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Cell line record created/matched on receipt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reagent_request",
                to="pipeline.cellline",
            ),
        ),
        migrations.AlterField(
            model_name="reagentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("shipped", "Shipped"),
                    ("received", "Received"),
                    ("not_sent", "Not Sent / Removed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ManufacturerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "custom_message",
                    models.TextField(
                        blank=True,
                        help_text="Personalised note included in request emails to this contact",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes (not sent in emails)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="pipeline.company",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which YCharOS site this contact serves (blank = all sites)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manufacturer_contacts",
                        to="pipeline.site",
                    ),
                ),
            ],
            options={
                "ordering": ["company__name", "contact_name"],
            },
        ),
        migrations.CreateModel(
            name="ReagentRequestBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. 'April 2024 GBA1 Canada antibodies'",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("partial", "Partially Received"),
                            ("complete", "Complete"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When request emails were sent to manufacturers",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_batches_created",
                        to="pipeline.member",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_batches",
                        to="pipeline.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="request_batches",
                        to="pipeline.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reagent request batch",
                "verbose_name_plural": "Reagent request batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for unexpected arrivals logged directly at receipt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="pipeline.reagentrequestbatch",
            ),
        ),
    ]
