# Generated by Django 5.1 on 2026-04-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0014_alter_reagentrequest_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reagentrequest",
            name="antibody",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="catalogue_number",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="cell_line",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="received_by",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="received_catalogue_number",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="received_clonality",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="received_clone_id",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="received_concentration",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="received_date",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="received_host",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="received_isotype",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="received_lot_number",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="received_notes",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="received_quantity",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="received_storage_location",
        ),
        migrations.RemoveField(
            model_name="reagentrequest",
            name="shipped_date",
        ),
        migrations.AddField(
            model_name="reagentrequest",
            name="catalogue_numbers",
            field=models.TextField(
                blank=True,
                help_text="One catalogue number per line, or blank for open requests",
            ),
        ),
        migrations.AlterField(
            model_name="reagentrequest",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for items logged outside a batch",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="pipeline.reagentrequestbatch",
            ),
        ),
        migrations.AlterField(
            model_name="reagentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("received", "Received"),
                    ("not_sent", "Not Sent"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
