# Generated by Django 5.1 on 2026-07-14 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0015_remove_reagentrequest_antibody_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CropperSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_username", models.CharField(db_index=True, max_length=150)),
                ("gene", models.CharField(blank=True, max_length=255)),
                ("cell_line", models.CharField(blank=True, max_length=255)),
                ("genotype", models.CharField(default="KO", max_length=4)),
                ("fc_secondary", models.BooleanField(default=False)),
                ("uniprot_id", models.CharField(blank=True, max_length=50)),
                ("protein_name", models.CharField(blank=True, max_length=255)),
                ("antibody_list", models.TextField(blank=True)),
                ("overwrite_ack", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cropper session",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CropperImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("application_type", models.CharField(default="WB", max_length=10)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("image", models.FileField(upload_to="cropper_staging/%Y/%m/")),
                ("nat_w", models.IntegerField(default=0)),
                ("nat_h", models.IntegerField(default=0)),
                ("grid", models.JSONField(blank=True, default=dict)),
                ("mapping", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="pipeline.croppersession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cropper image",
                "ordering": ["order", "id"],
            },
        ),
    ]
