# Generated by Django 5.1 on 2026-07-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0016_croppersession_cropperimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="croppersession",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
