# Generated by Django 5.1 on 2026-07-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0017_croppersession_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="croppersession",
            name="recommended",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
