# Generated by Django 5.1 on 2026-07-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0018_croppersession_recommended"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorizonKoLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gene_name", models.CharField(db_index=True, max_length=100)),
                (
                    "item_number",
                    models.CharField(
                        help_text="Horizon catalogue/item number, e.g. HZGHC000001c010",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="Horizon product description, e.g. 'Human ARAF 5bp deletion knockout cell line'",
                        max_length=255,
                    ),
                ),
                (
                    "supplier",
                    models.CharField(default="Horizon Discovery", max_length=100),
                ),
                ("background", models.CharField(default="HAP1", max_length=50)),
                ("dataset_version", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "ordering": ["gene_name", "item_number"],
                "indexes": [
                    models.Index(
                        fields=["gene_name"], name="pipeline_ho_gene_na_9f164b_idx"
                    )
                ],
            },
        ),
    ]
