# Generated by Django 5.1 on 2026-07-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0019_horizonkoline"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="f1000_note",
            field=models.CharField(
                blank=True,
                help_text="Where the F1000 column says something that isn't a link ('coming', 'publish elsewhere') — kept rather than discarded",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="f1000_priority",
            field=models.CharField(
                blank=True,
                help_text="Free text: is this queued for an F1000 write-up, and any caveat (e.g. 'YES with IF repeat'). Carl's target-list column R.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="target",
            name="essential_gene",
            field=models.CharField(
                blank=True,
                help_text="Is this an essential gene per DepMap? 'YES' / 'NO' / 'slightly'",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TargetClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(db_index=True, max_length=80)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("uniprot", "UniProt keyword"),
                            ("go", "GO term"),
                            ("family", "Gene family"),
                            ("manual", "Added by hand"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "evidence",
                    models.CharField(
                        blank=True,
                        help_text="The raw keyword / GO term the label came from",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classifications",
                        to="pipeline.target",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("target", "label", "source"),
                        name="unique_target_class_per_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TargetNomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("funded", models.BooleanField(default=False)),
                ("date_of_nomination", models.DateField(blank=True, null=True)),
                (
                    "date_text",
                    models.CharField(
                        blank=True,
                        help_text="What the source actually said when it wasn't a real date ('2020', 'april 2024') — kept so nothing is silently invented",
                        max_length=50,
                    ),
                ),
                ("comments", models.CharField(blank=True, max_length=255)),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Who nominated it / who to ask",
                        max_length=255,
                    ),
                ),
                ("status_note", models.CharField(blank=True, max_length=120)),
                ("conclusion_note", models.CharField(blank=True, max_length=120)),
                ("antibodies_requested", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nominations_created",
                        to="pipeline.member",
                    ),
                ),
                (
                    "granting_agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nominations",
                        to="pipeline.grantingagency",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nominations",
                        to="pipeline.project",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which YCharOS site is pursuing it — the key to spotting the same target funded at two sites",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nominations",
                        to="pipeline.site",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to="pipeline.target",
                    ),
                ),
            ],
            options={
                "ordering": ["target__gene_name", "project__name"],
                "indexes": [
                    models.Index(
                        fields=["funded"], name="pipeline_ta_funded_c38127_idx"
                    ),
                    models.Index(
                        fields=["site", "funded"], name="pipeline_ta_site_id_794af9_idx"
                    ),
                ],
            },
        ),
    ]
