# Generated by Django 5.1 on 2026-08-04 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0021_alter_fileattachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileattachment",
            name="checksum_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
