# Generated by Django 5.1 on 2026-08-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0022_fileattachment_checksum_sha256"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Filename this capture is served as, e.g. oga_pipeline_snapshot_20260804T031700Z.json.gz",
                        max_length=120,
                        unique=True,
                    ),
                ),
                ("taken", models.DateTimeField(db_index=True)),
                ("blob", models.BinaryField(help_text="The capture, gzipped.")),
                (
                    "byte_size",
                    models.PositiveIntegerField(help_text="Size of the gzipped blob."),
                ),
                ("row_total", models.PositiveIntegerField(default=0)),
                ("table_count", models.PositiveIntegerField(default=0)),
                ("format_version", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "dataset snapshot",
                "ordering": ["-taken"],
            },
        ),
    ]
