# Generated by Django 5.1 on 2026-08-13 14:47

import django.db.models.deletion
import pipeline.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0023_datasetsnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingPublicationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("WB", "Western Blot"),
                            ("IP", "Immunoprecipitation"),
                            ("ICC-IF", "Immunocytochemistry/IF"),
                            ("FC", "Flow Cytometry"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        help_text="The crop as it would appear on the public gene page.",
                        storage=pipeline.storages.attachment_storage,
                        upload_to="pending_figures/%Y/%m/",
                    ),
                ),
                ("recommended", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting release"),
                            ("released", "Released to the public site"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("staged_by", models.CharField(blank=True, max_length=150)),
                ("released_by", models.CharField(blank=True, max_length=150)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_images",
                        to="pipeline.antibody",
                    ),
                ),
                (
                    "source_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="The cropper session this crop came from, if it still exists.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_images",
                        to="pipeline.croppersession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending publication image",
                "verbose_name_plural": "Pending publication images",
                "ordering": [
                    "antibody__target__gene_name",
                    "antibody__catalogue_number",
                    "application_type",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("antibody", "application_type"),
                        name="unique_pending_image_per_antibody_app",
                    )
                ],
            },
        ),
    ]
