# Generated by Django 5.1 on 2026-08-23 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0024_pending_publication_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("typed_text", models.CharField(max_length=120)),
                (
                    "gene_symbol",
                    models.CharField(blank=True, db_index=True, max_length=40),
                ),
                ("uniprot_id", models.CharField(blank=True, max_length=20)),
                ("protein_name", models.CharField(blank=True, max_length=255)),
                ("applications", models.CharField(blank=True, max_length=60)),
                ("email", models.EmailField(max_length=254)),
                ("requester_name", models.CharField(blank=True, max_length=120)),
                ("organisation", models.CharField(blank=True, max_length=160)),
                ("has_funding", models.BooleanField(default=False)),
                ("funding_note", models.TextField(blank=True)),
                ("note", models.TextField(blank=True)),
                (
                    "checked",
                    models.CharField(
                        choices=[
                            ("human", "Confirmed human protein in UniProt"),
                            ("unchecked", "UniProt could not be reached"),
                        ],
                        default="human",
                        max_length=12,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "target",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="public_requests",
                        to="pipeline.target",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["gene_symbol"], name="pipeline_ge_gene_sy_fccab6_idx"
                    )
                ],
            },
        ),
    ]
