# Generated by Django 5.1 on 2026-08-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0025_generequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="generequest",
            name="applications_other",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
