# Generated by Django 5.1 on 2026-08-28 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0027_staged_crops_at_their_public_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="AntibodyOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("WB", "Western Blot"),
                            ("IP", "Immunoprecipitation"),
                            ("ICC-IF", "Immunocytochemistry/IF"),
                            ("FC", "Flow Cytometry"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "detects",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("unclear", "Could not tell"),
                            ("no_selective_signal", "No selective signal"),
                            ("selective", "Selective"),
                            ("strongly_selective", "Strongly selective"),
                        ],
                        help_text="Does it detect the target? (SpecificSignal)",
                        max_length=20,
                    ),
                ),
                (
                    "selective",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("unclear", "Could not tell"),
                            ("no_selective_signal", "No selective signal"),
                            ("selective", "Selective"),
                            ("strongly_selective", "Strongly selective"),
                        ],
                        help_text="Is it selective for the target? (SelectiveSignal)",
                        max_length=20,
                    ),
                ),
                (
                    "enriches",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("no", "No"),
                            ("unclear", "Could not tell"),
                            ("no_selective_signal", "No selective signal"),
                            ("selective", "Selective"),
                            ("strongly_selective", "Strongly selective"),
                        ],
                        help_text="Did it pull the target down? (IP Enrichment)",
                        max_length=20,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="What the reviewer saw. Free text, beside the judgement.",
                    ),
                ),
                ("assessed_by", models.CharField(blank=True, max_length=150)),
                ("assessed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcomes",
                        to="pipeline.antibody",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antibody outcome",
                "verbose_name_plural": "Antibody outcomes",
                "ordering": [
                    "antibody__target__gene_name",
                    "antibody__catalogue_number",
                    "application_type",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("antibody", "application_type"),
                        name="unique_outcome_per_antibody_app",
                    )
                ],
            },
        ),
    ]
