# Generated by Django 5.1 on 2026-08-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0028_antibody_outcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="antibody",
            name="recommendations_set_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When any OGA recommendation for this antibody last changed.",
                null=True,
            ),
        ),
    ]
