# Generated by Django 5.1 on 2026-09-18.
#
# Knockdown as a kind of control. Every operation is additive — seven blank
# text columns and a widened choice list — so a rollback to the previous code
# leaves the columns in place and unread (CLAUDE.md, "Falling back to an older
# commit"). The AlterField carries only the new `KD` choice: `choices` is not a
# database attribute, so it is a no-op on PostgreSQL and rebuilds no table on
# SQLite. Nothing here backfills; `backfill_control_genotype` does that from
# the Access export, dry-run by default.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0031_antibody_received_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="cellline",
            name="knockdown_catalogue",
            field=models.CharField(
                blank=True,
                help_text="The reagent's catalogue number or pool ID, e.g. L-012345-00-0005",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="knockdown_method",
            field=models.CharField(
                blank=True,
                help_text="siRNA, shRNA, CRISPRi, antisense oligo — how the transcript is suppressed",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="knockdown_sequence",
            field=models.TextField(
                blank=True, help_text="Target sequence(s), or the pool's individual IDs"
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="knockdown_supplier",
            field=models.CharField(
                blank=True,
                help_text="Who made the silencing reagent, e.g. Dharmacon / Horizon",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="transfection_reagent",
            field=models.CharField(
                blank=True,
                help_text="What carried the reagent into the cells, e.g. Lipofectamine RNAiMAX",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="pendingpublicationimage",
            name="control_genotype",
            field=models.CharField(
                blank=True,
                choices=[("KO", "Knockout"), ("KD", "Knockdown")],
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="publicationimage",
            name="control_genotype",
            field=models.CharField(
                blank=True,
                choices=[("KO", "Knockout"), ("KD", "Knockdown")],
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="cellline",
            name="genotype",
            field=models.CharField(
                choices=[
                    ("WT", "Wild Type"),
                    ("KO", "Knockout"),
                    ("KD", "Knockdown"),
                    ("other", "Other"),
                ],
                default="WT",
                max_length=10,
            ),
        ),
    ]
