# Generated by Django 5.1 on 2026-09-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0032_knockdown_lines_and_figure_control"),
    ]

    operations = [
        migrations.AddField(
            model_name="antibodyoutcome",
            name="background",
            field=models.CharField(
                blank=True,
                choices=[
                    ("yes", "Yes"),
                    ("no", "No"),
                    ("unclear", "Could not tell"),
                    ("no_selective_signal", "No selective signal"),
                    ("selective", "Selective"),
                    ("strongly_selective", "Strongly selective"),
                ],
                help_text="Flow cytometry: is there non-specific background?",
                max_length=20,
            ),
        ),
    ]
