# Generated by Django 5.1 on 2026-09-26 01:24
#
# Whole IHC figures for a gene's public IHC page (26 Sep 2026): four new
# tables and nothing else. Purely additive, so a rollback runs old code that
# never reads them. It reaches live PostgreSQL unattended in pre-deploy, and CI
# (SQLite) does not vouch for it. Never RemoveField/RenameField these later.

import django.db.models.deletion
import pipeline.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0035_antibody_ihc_recommended"),
    ]

    operations = [
        migrations.CreateModel(
            name="IhcFigure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=140)),
                ("label", models.CharField(max_length=120)),
                ("legend", models.TextField()),
                ("image", models.FileField(max_length=255, upload_to="ihc_figures/")),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("samples", models.JSONField(blank=True, default=dict)),
                ("controls", models.JSONField(blank=True, default=list)),
                ("supplier_key", models.BooleanField(default=False)),
                ("scale", models.CharField(blank=True, max_length=60)),
                ("source", models.CharField(blank=True, max_length=300)),
                (
                    "control_genotype",
                    models.CharField(
                        blank=True,
                        choices=[("KO", "Knockout"), ("KD", "Knockdown")],
                        max_length=4,
                    ),
                ),
                ("released_by", models.CharField(blank=True, max_length=150)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ihc_figures",
                        to="pipeline.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whole IHC figure",
                "verbose_name_plural": "Whole IHC figures",
                "ordering": ["target__gene_name", "slug"],
            },
        ),
        migrations.CreateModel(
            name="IhcFigureAntibody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "antibody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ihc_figure_links",
                        to="pipeline.antibody",
                    ),
                ),
                (
                    "figure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antibody_links",
                        to="pipeline.ihcfigure",
                    ),
                ),
            ],
            options={
                "ordering": ["figure", "position", "id"],
            },
        ),
        migrations.AddField(
            model_name="ihcfigure",
            name="antibodies",
            field=models.ManyToManyField(
                blank=True,
                related_name="ihc_figures",
                through="pipeline.IhcFigureAntibody",
                to="pipeline.antibody",
            ),
        ),
        migrations.CreateModel(
            name="PendingIhcFigure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=140)),
                ("label", models.CharField(max_length=120)),
                ("legend", models.TextField()),
                (
                    "image",
                    models.FileField(
                        help_text="The whole figure, byte for byte, on private storage.",
                        max_length=255,
                        storage=pipeline.storages.attachment_storage,
                        upload_to="ihc_figures_pending/",
                    ),
                ),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("samples", models.JSONField(blank=True, default=dict)),
                ("controls", models.JSONField(blank=True, default=list)),
                ("supplier_key", models.BooleanField(default=False)),
                ("scale", models.CharField(blank=True, max_length=60)),
                ("source", models.CharField(blank=True, max_length=300)),
                (
                    "control_genotype",
                    models.CharField(
                        blank=True,
                        choices=[("KO", "Knockout"), ("KD", "Knockdown")],
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting release"),
                            ("released", "Released to the public site"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("staged_by", models.CharField(blank=True, max_length=150)),
                ("released_by", models.CharField(blank=True, max_length=150)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_ihc_figures",
                        to="pipeline.croppersession",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_ihc_figures",
                        to="pipeline.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending whole IHC figure",
                "verbose_name_plural": "Pending whole IHC figures",
                "ordering": ["target__gene_name", "slug"],
            },
        ),
        migrations.CreateModel(
            name="PendingIhcFigureAntibody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "antibody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_ihc_figure_links",
                        to="pipeline.antibody",
                    ),
                ),
                (
                    "figure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antibody_links",
                        to="pipeline.pendingihcfigure",
                    ),
                ),
            ],
            options={
                "ordering": ["figure", "position", "id"],
            },
        ),
        migrations.AddField(
            model_name="pendingihcfigure",
            name="antibodies",
            field=models.ManyToManyField(
                blank=True,
                related_name="pending_ihc_figures",
                through="pipeline.PendingIhcFigureAntibody",
                to="pipeline.antibody",
            ),
        ),
        migrations.AddConstraint(
            model_name="ihcfigureantibody",
            constraint=models.UniqueConstraint(
                fields=("figure", "antibody"), name="unique_ihc_figure_antibody"
            ),
        ),
        migrations.AddConstraint(
            model_name="ihcfigure",
            constraint=models.UniqueConstraint(
                fields=("target", "slug"), name="unique_ihc_figure_per_target_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingihcfigureantibody",
            constraint=models.UniqueConstraint(
                fields=("figure", "antibody"), name="unique_pending_ihc_figure_antibody"
            ),
        ),
        migrations.AddConstraint(
            model_name="pendingihcfigure",
            constraint=models.UniqueConstraint(
                fields=("target", "slug"),
                name="unique_pending_ihc_figure_per_target_slug",
            ),
        ),
    ]
