# IHC at the bench (26 Sep 2026, PLATFORM_ROADMAP #102): a fifth procedure
# code, `IHC`, and a per-antibody result table modelled on `IfResult`.
#
# Every operation is additive and rollback-safe on PostgreSQL:
# - the two `procedure_type` columns widen varchar(2) -> varchar(3) (a
#   metadata-only change on PostgreSQL; nothing is rewritten or narrowed);
# - the choice-list changes emit no SQL;
# - `IhcResult` is a new table and `fileattachment.ihc_result` a nullable FK,
#   so no NOT NULL column is added and the `db_default` trap does not apply.
#
# What a rollback does NOT undo: once somebody has saved an IHC session, the
# older code opening it hits `MAP["IHC"]` lookups it does not have. Roll back
# only before an IHC session exists, or roll forward.
# Generated by Django 5.1 on 2026-09-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0037_cropper_image_private_storage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentsession",
            name="procedure_type",
            field=models.CharField(
                choices=[
                    ("WB", "Western Blot"),
                    ("IP", "Immunoprecipitation"),
                    ("IF", "Immunofluorescence"),
                    ("FC", "Flow Cytometry"),
                    ("IHC", "Immunohistochemistry"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="fileattachment",
            name="category",
            field=models.CharField(
                choices=[
                    ("wb_scan", "WB Scan"),
                    ("wb_composite", "WB Composite Panel"),
                    ("ponceau", "Ponceau S Stain"),
                    ("if_image", "IF Image"),
                    ("if_plate", "IF Plate Overview"),
                    ("fc_histogram", "FC Histogram"),
                    ("fc_fcs", "FC Raw Data (.fcs)"),
                    ("ip_scan", "IP Scan"),
                    ("ihc_image", "IHC Image"),
                    ("ihc_slide", "IHC Slide / TMA Scan"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="protocoltemplate",
            name="procedure_type",
            field=models.CharField(
                choices=[
                    ("WB", "Western Blot"),
                    ("IP", "Immunoprecipitation"),
                    ("IF", "Immunofluorescence"),
                    ("FC", "Flow Cytometry"),
                    ("IHC", "Immunohistochemistry"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="targetassignment",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("WB", "Western Blot"),
                    ("IP", "Immunoprecipitation"),
                    ("IF", "Immunofluorescence"),
                    ("FC", "Flow Cytometry"),
                    ("IHC", "Immunohistochemistry"),
                    ("KO", "KO Cell Line Generation"),
                ],
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="IhcResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specific_signal", models.CharField(blank=True, max_length=255)),
                (
                    "staining_location",
                    models.CharField(
                        blank=True,
                        help_text="e.g. cytoplasmic, nuclear, membranous",
                        max_length=255,
                    ),
                ),
                ("primary_ab_dilution", models.CharField(blank=True, max_length=255)),
                (
                    "dilution_source",
                    models.CharField(
                        blank=True,
                        help_text="Where the dilution came from, e.g. supplier-recommended",
                        max_length=255,
                    ),
                ),
                (
                    "secondary_ab",
                    models.CharField(
                        blank=True,
                        help_text="Secondary / detection, e.g. OmniMap anti-rabbit HRP",
                        max_length=255,
                    ),
                ),
                (
                    "slide_position",
                    models.CharField(
                        blank=True,
                        help_text="Slide or TMA core position",
                        max_length=100,
                    ),
                ),
                ("image_acquired_by", models.CharField(blank=True, max_length=255)),
                ("image_analysed_by", models.CharField(blank=True, max_length=255)),
                ("tissue_result", models.TextField(blank=True)),
                ("comments", models.TextField(blank=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ihc_results",
                        to="pipeline.antibody",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ihc_results",
                        to="pipeline.experimentsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "IHC result",
                "verbose_name_plural": "IHC results",
            },
        ),
        migrations.AddField(
            model_name="fileattachment",
            name="ihc_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attachments",
                to="pipeline.ihcresult",
            ),
        ),
    ]
