# Generated by Django 5.1 on 2026-09-27 13:04

import pipeline.saved_by
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0038_ihc_bench_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="antibody",
            name="added_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever created this row through the website, or command:<name> for a management command. Blank = not recorded (every row saved before 27 Sep 2026).",
                max_length=150,
                on_add=True,
            ),
        ),
        migrations.AddField(
            model_name="antibody",
            name="saved_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever last saved this row; see added_by.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="added_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever created this row through the website, or command:<name> for a management command. Blank = not recorded (every row saved before 27 Sep 2026).",
                max_length=150,
                on_add=True,
            ),
        ),
        migrations.AddField(
            model_name="cellline",
            name="saved_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever last saved this row; see added_by.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="experimentsession",
            name="added_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever created this row through the website, or command:<name> for a management command. Blank = not recorded (every row saved before 27 Sep 2026).",
                max_length=150,
                on_add=True,
            ),
        ),
        migrations.AddField(
            model_name="experimentsession",
            name="saved_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever last saved this row; see added_by.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="fcresult",
            name="added_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever created this row through the website, or command:<name> for a management command. Blank = not recorded (every row saved before 27 Sep 2026).",
                max_length=150,
                on_add=True,
            ),
        ),
        migrations.AddField(
            model_name="fcresult",
            name="saved_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever last saved this row; see added_by.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="ifresult",
            name="added_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever created this row through the website, or command:<name> for a management command. Blank = not recorded (every row saved before 27 Sep 2026).",
                max_length=150,
                on_add=True,
            ),
        ),
        migrations.AddField(
            model_name="ifresult",
            name="saved_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever last saved this row; see added_by.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="ihcresult",
            name="added_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever created this row through the website, or command:<name> for a management command. Blank = not recorded (every row saved before 27 Sep 2026).",
                max_length=150,
                on_add=True,
            ),
        ),
        migrations.AddField(
            model_name="ihcresult",
            name="saved_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever last saved this row; see added_by.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="ipresult",
            name="added_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever created this row through the website, or command:<name> for a management command. Blank = not recorded (every row saved before 27 Sep 2026).",
                max_length=150,
                on_add=True,
            ),
        ),
        migrations.AddField(
            model_name="ipresult",
            name="saved_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever last saved this row; see added_by.",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="wbresult",
            name="added_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever created this row through the website, or command:<name> for a management command. Blank = not recorded (every row saved before 27 Sep 2026).",
                max_length=150,
                on_add=True,
            ),
        ),
        migrations.AddField(
            model_name="wbresult",
            name="saved_by",
            field=pipeline.saved_by.SavedByField(
                blank=True,
                db_default="",
                default="",
                editable=False,
                help_text="Username of whoever last saved this row; see added_by.",
                max_length=150,
            ),
        ),
    ]
