# Generated by Django 5.1 on 2026-09-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0042_unnumber_knockdown_lines"),
    ]

    operations = [
        migrations.CreateModel(
            name="JudgementChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("antibody_id", models.IntegerField(db_index=True)),
                ("catalogue_number", models.CharField(blank=True, max_length=255)),
                ("gene", models.CharField(blank=True, db_index=True, max_length=100)),
                ("application_type", models.CharField(max_length=10)),
                ("field", models.CharField(max_length=20)),
                ("queued", models.BooleanField(default=False)),
                ("old_value", models.TextField(blank=True)),
                ("new_value", models.TextField(blank=True)),
                ("changed_by", models.CharField(blank=True, max_length=150)),
                ("source", models.CharField(blank=True, max_length=200)),
                ("changed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Judgement change",
                "verbose_name_plural": "Judgement changes",
                "ordering": ["-changed_at", "-id"],
            },
        ),
    ]
