# Generated by Django 5.1 on 2026-09-30 20:02

# Two new tables and nothing else: no existing column is altered, no RunPython.
# A rollback to the previous commit leaves them unread, which is harmless. The
# rows are written by `manage.py load_methods_record`, never by this migration.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0043_judgement_change"),
    ]

    operations = [
        migrations.CreateModel(
            name="MethodsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application",
                    models.CharField(
                        choices=[
                            ("WB", "Western Blot"),
                            ("IP", "Immunoprecipitation"),
                            ("ICC-IF", "Immunocytochemistry/IF"),
                            ("FC", "Flow Cytometry"),
                            ("IHC", "Immunohistochemistry"),
                        ],
                        max_length=10,
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("report_file", models.CharField(blank=True, max_length=255)),
                ("source_ref", models.CharField(blank=True, max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods_records",
                        to="pipeline.target",
                    ),
                ),
            ],
            options={
                "verbose_name": "methods record",
            },
        ),
        migrations.CreateModel(
            name="AntibodyMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(blank=True, max_length=120)),
                (
                    "basis",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("report_named", "Named with its value in the report"),
                            ("report_protocol", "Protocol amount for every antibody"),
                            ("report_general", "General statement in the report"),
                            ("lab_record", "The lab's own record"),
                        ],
                        max_length=20,
                    ),
                ),
                ("where", models.CharField(blank=True, max_length=255)),
                ("source_ref", models.CharField(blank=True, max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "antibody",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="pipeline.antibody",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="antibodies",
                        to="pipeline.methodsrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "antibody method",
            },
        ),
        migrations.AddConstraint(
            model_name="methodsrecord",
            constraint=models.UniqueConstraint(
                fields=("target", "application"), name="unique_methods_per_target_app"
            ),
        ),
    ]
