# Generated by Django 5.1 on 2025-01-06 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antibody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('wb_image', models.ImageField(blank=True, null=True, upload_to='gene_experiments/')),
                ('ip_image', models.ImageField(blank=True, null=True, upload_to='gene_experiments/')),
                ('icc_if_image', models.ImageField(blank=True, null=True, upload_to='gene_experiments/')),
                ('fc_image', models.ImageField(blank=True, null=True, upload_to='gene_experiments/')),
                ('f1000_report_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrid', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('clonality', models.CharField(blank=True, max_length=100, null=True)),
                ('recombinant', models.CharField(blank=True, max_length=100, null=True)),
                ('antibody', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='core.antibody')),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_type', models.CharField(choices=[('WB', 'Western Blot'), ('IP', 'Immunoprecipitation'), ('ICC-IF', 'Immunocytochemistry/IF'), ('FC', 'Flow Cytometry')], max_length=50)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='experiments/')),
                ('antibody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='core.antibody')),
            ],
        ),
        migrations.AddField(
            model_name='antibody',
            name='gene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antibodies', to='core.gene'),
        ),
    ]
