# Generated by Django 5.1 on 2025-02-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='product_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
