# Generated by Django 5.1 on 2025-02-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_description_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='citation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
