# Generated by Django 5.1 on 2025-03-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gene_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='clone_ID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
