# Generated by Django 5.1 on 2025-04-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_description_clone_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='recomended_applications',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
