# Generated by Django 5.1 on 2025-05-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_description_recomended_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='discontinued',
            field=models.BooleanField(default=False),
        ),
    ]
