# Generated by Django 5.1 on 2025-11-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_description_discontinued'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='recomended_applications',
        ),
        migrations.AddField(
            model_name='description',
            name='fc_app',
            field=models.BooleanField(default=False, verbose_name='Flow Cytometry (FC)'),
        ),
        migrations.AddField(
            model_name='description',
            name='icc_if_app',
            field=models.BooleanField(default=False, verbose_name='ICC / IF'),
        ),
        migrations.AddField(
            model_name='description',
            name='ip_app',
            field=models.BooleanField(default=False, verbose_name='Immunoprecipitation (IP)'),
        ),
        migrations.AddField(
            model_name='description',
            name='wb_app',
            field=models.BooleanField(default=False, verbose_name='Western Blot'),
        ),
    ]
