# Generated by Django 5.1 on 2025-11-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_description_recomended_applications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the cell line (e.g., HeLa, HEK293, A549)', max_length=150, unique=True)),
                ('purchase_link', models.URLField(blank=True, help_text='Optional link to purchase or learn more about this cell line', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='gene',
            name='cell_lines',
            field=models.ManyToManyField(blank=True, help_text='Cell lines used for this gene experiment', related_name='genes', to='core.cellline'),
        ),
    ]
