# Generated by Django 5.1 on 2025-11-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cellline_gene_cell_lines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gene',
            name='cell_lines',
        ),
        migrations.AddField(
            model_name='gene',
            name='cell_line_link',
            field=models.URLField(blank=True, help_text='Link to the cell line used for this gene', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='f1000_report_link',
            field=models.URLField(blank=True, help_text='Link to the external F1000 report for this gene', null=True),
        ),
    ]
