# Generated by Django 5.1 on 2026-03-25 16:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_gene_aliases"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIConsumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Organisation name (e.g. 'Abcam', 'Antibody Registry')",
                        max_length=255,
                    ),
                ),
                (
                    "api_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Auto-generated API key — share with the consumer",
                        unique=True,
                    ),
                ),
                (
                    "consumer_type",
                    models.CharField(
                        choices=[
                            ("manufacturer", "Manufacturer"),
                            ("rrid", "RRID / Registry"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "supplier_filter",
                    models.CharField(
                        blank=True,
                        help_text="For manufacturers: exact match on Description.supplier field (e.g. 'Abcam', 'Cell Signaling Technology'). Ignored for RRID consumers.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "last_queried_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Auto-updated each time this consumer calls the API",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "API Consumer",
                "verbose_name_plural": "API Consumers",
            },
        ),
        migrations.AddField(
            model_name="antibody",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="experiment",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
