# Generated by Django 5.1 on 2026-03-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_apiconsumer_antibody_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconsumer",
            name="portal_config",
            field=models.JSONField(
                blank=True,
                help_text="Customer portal preferences: URL pattern, filename convention, image format, contact info, etc.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apiconsumer",
            name="supplier_filter",
            field=models.CharField(
                blank=True,
                help_text="For manufacturers: comma-separated list of supplier names to match (e.g. 'Bio-Techne,Bio-Techne (Novus Biologicals),Bio-Techne (R&D Systems)'). Must exactly match Description.supplier values. Ignored for RRID consumers.",
                max_length=500,
                null=True,
            ),
        ),
    ]
