# Generated by Django 5.1 on 2026-03-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_apiconsumer_portal_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconsumer",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free — embed cards and iframe strings only"),
                    ("data", "Data — bulk downloads, custom cards, SEO packages"),
                    ("intel", "Intel — data tier plus competitor benchmarking"),
                    ("full", "Full — all features including issue reporting"),
                ],
                default="free",
                help_text="Controls which portal features this consumer can access",
                max_length=20,
            ),
        ),
    ]
