# Generated by Django 5.1 on 2026-08-09 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_apiconsumer_gene_filter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiUsageDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "endpoint",
                    models.CharField(
                        help_text="URL name, e.g. 'antibodies_feed'.", max_length=64
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "consumer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Blank means the request carried no usable API key.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_days",
                        to="core.apiconsumer",
                    ),
                ),
            ],
            options={
                "verbose_name": "API usage (day)",
                "verbose_name_plural": "API usage (days)",
                "ordering": ["-date", "endpoint"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("consumer__isnull", False)),
                        fields=("consumer", "date", "endpoint"),
                        name="one_usage_row_per_consumer_day_endpoint",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("consumer__isnull", True)),
                        fields=("date", "endpoint"),
                        name="one_usage_row_per_keyless_day_endpoint",
                    ),
                ],
            },
        ),
    ]
