# Generated by Django 5.1 on 2026-08-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_retire_legacy_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="McpUsageDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "tool",
                    models.CharField(
                        help_text="MCP tool name, e.g. 'search_antibodies'.",
                        max_length=64,
                    ),
                ),
                (
                    "client",
                    models.CharField(
                        blank=True,
                        help_text="The MCP client's own name. Blank means it did not say.",
                        max_length=64,
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "MCP usage (day)",
                "verbose_name_plural": "MCP usage (days)",
                "ordering": ["-date", "tool"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "tool", "client"),
                        name="one_mcp_usage_row_per_day_tool_client",
                    )
                ],
            },
        ),
    ]
