# Generated by Django 5.1 on 2026-09-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_mcpusageday"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="mcpusageday",
            name="one_mcp_usage_row_per_day_tool_client",
        ),
        migrations.AddField(
            model_name="apiconsumer",
            name="is_internal",
            field=models.BooleanField(
                default=False,
                help_text="Ours — testing or demos. Kept out of the impact page's headline totals and counted separately beneath them.",
                verbose_name="Internal / test key",
            ),
        ),
        migrations.AddField(
            model_name="mcpusageday",
            name="internal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="mcpusageday",
            constraint=models.UniqueConstraint(
                fields=("date", "tool", "client", "internal"),
                name="one_mcp_usage_row_per_day_tool_client_origin",
            ),
        ),
    ]
