# Generated by Django 5.1 on 2026-09-29 18:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_mcp_usage_internal_and_consumer_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconsumer",
            name="email_domains",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Comma-separated email domains (e.g. 'abcam.com') whose addresses are sent this organisation's key on request. The key is shared: a request never creates a second one.",
                max_length=500,
            ),
        ),
        migrations.CreateModel(
            name="KeyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("organisation", models.CharField(blank=True, max_length=200)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            (
                                "sent",
                                "Key emailed — the address is on the organisation's domain",
                            ),
                            (
                                "unmatched",
                                "No organisation on file for this domain — passed to OGA",
                            ),
                            ("refused", "Personal email provider — refused"),
                            ("failed", "Matched, but the email could not be sent"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="key_requests",
                        to="core.apiconsumer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Key request",
                "verbose_name_plural": "Key requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierMailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("launch", "First summary"), ("update", "Update")],
                        max_length=10,
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("subject", models.CharField(max_length=300)),
                ("recipients", models.TextField(help_text="To, then Cc, as sent.")),
                ("attachment", models.CharField(blank=True, max_length=200)),
                ("antibodies", models.PositiveIntegerField(default=0)),
                ("not_supportive", models.PositiveIntegerField(default=0)),
                (
                    "changes",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Results new or changed since the previous email.",
                    ),
                ),
                ("fingerprint", models.JSONField(default=dict)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailings",
                        to="core.apiconsumer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier mailing",
                "verbose_name_plural": "Supplier mailings",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[("to", "To"), ("cc", "Cc")], default="to", max_length=2
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to stop emailing this person without losing the row.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consumer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="core.apiconsumer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier contact",
                "verbose_name_plural": "Supplier contacts",
                "ordering": ["consumer__name", "role", "email"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consumer", "email"),
                        name="one_contact_row_per_consumer_email",
                    )
                ],
            },
        ),
    ]
