# Generated by Django 5.1 on 2026-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_supplier_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suppliermailing",
            name="kind",
            field=models.CharField(
                choices=[
                    ("launch", "First summary"),
                    ("update", "Update"),
                    ("resend", "Summary resent"),
                ],
                max_length=10,
            ),
        ),
    ]
