# Generated by Django 5.1 on 2026-07-22 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SelectionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academy_user_id",
                    models.IntegerField(
                        blank=True,
                        help_text="auth_user PK when the run was authenticated (future: behind login).",
                        null=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("target_gene", models.CharField(blank=True, max_length=120)),
                ("species", models.CharField(blank=True, max_length=60)),
                ("application", models.CharField(blank=True, max_length=40)),
                ("question_type", models.CharField(blank=True, max_length=40)),
                ("decision", models.CharField(blank=True, max_length=40)),
                ("plan", models.JSONField(blank=True, null=True)),
                ("guidance", models.JSONField(blank=True, null=True)),
                ("completed", models.BooleanField(default=False)),
                (
                    "pack_version",
                    models.CharField(default="selector-0.1.0", max_length=40),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
