# Generated by Django 5.1 on 2026-07-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selector", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="selectionrecord",
            name="institution",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="selectionrecord",
            name="is_compliance",
            field=models.BooleanField(default=False),
        ),
    ]
