# Generated by Django 5.1 on 2026-07-16 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PendingClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("institutional_email", models.EmailField(max_length=254)),
                ("modules", models.JSONField(blank=True, default=list)),
                ("target_gene", models.CharField(blank=True, max_length=100)),
                ("rrid", models.CharField(blank=True, max_length=50)),
                ("plan", models.JSONField(blank=True, null=True)),
                ("pack_version", models.CharField(blank=True, max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("module", "Learning module"),
                            ("workshop", "Antibody Validation Workshop"),
                            ("capstone", "Full Certification (capstone)"),
                        ],
                        default="workshop",
                        max_length=20,
                    ),
                ),
                ("recipient_name", models.CharField(max_length=200)),
                ("institutional_email", models.EmailField(max_length=254)),
                ("module_id", models.CharField(blank=True, max_length=50)),
                ("module_title", models.CharField(blank=True, max_length=200)),
                ("target_gene", models.CharField(blank=True, max_length=100)),
                ("rrid", models.CharField(blank=True, max_length=50)),
                ("plan", models.JSONField(blank=True, null=True)),
                ("pack_version", models.CharField(blank=True, max_length=30)),
                ("score", models.FloatField(default=100.0)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pending_claim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificates",
                        to="credentials.pendingclaim",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
    ]
