# Generated by Django 5.1 on 2025-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_lesson_slug_alter_lesson_order_lessonsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
