# Generated by Django 5.1 on 2025-11-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_sectionprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='has_quiz',
            field=models.BooleanField(default=True),
        ),
    ]
