# Generated by Django 5.1 on 2026-10-03 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0010_module_editor"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalibrationRater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("domain", models.CharField(db_index=True, max_length=200)),
                ("organisation", models.CharField(blank=True, max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Student"),
                            ("postdoc", "Postdoctoral researcher"),
                            ("pi", "Group leader / PI"),
                            ("staff", "Technician or staff scientist"),
                            ("industry", "Industry scientist"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "wb_experience",
                    models.CharField(
                        choices=[
                            ("none", "I have not run or interpreted western blots"),
                            ("some", "Occasionally: fewer than about 20 blots"),
                            ("regular", "Regularly: western blot is part of my work"),
                            (
                                "expert",
                                "Expert: I troubleshoot, train others or review blots",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("wb_years", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "ko_experience",
                    models.BooleanField(
                        default=False,
                        help_text="Has interpreted knockout-controlled western blots before",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CalibrationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("before", "After reading the criteria"),
                            ("after", "After rating the blots"),
                        ],
                        max_length=10,
                    ),
                ),
                ("clarity", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="academy.calibrationrater",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CalibrationRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.CharField(db_index=True, max_length=16)),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("main", "Detects the target as the main signal"),
                            (
                                "other",
                                "Detects the target, with strong or numerous other bands",
                            ),
                            ("none", "No clear target-specific signal"),
                            ("unsure", "Unsure"),
                        ],
                        max_length=10,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500)),
                ("seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="academy.calibrationrater",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rater", "item_id"), name="one_rating_per_rater_item"
                    )
                ],
            },
        ),
    ]
