"""
Django settings for OGA_website project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')

# In-app AI assistant (academy chat) — cost guardrails, all env-overridable.
ACADEMY_AI_MODEL = os.environ.get('ACADEMY_AI_MODEL', 'claude-haiku-4-5')
ACADEMY_AI_DAILY_MESSAGE_CAP = int(os.environ.get('ACADEMY_AI_DAILY_MESSAGE_CAP', '40'))
ACADEMY_AI_MAX_TOKENS = int(os.environ.get('ACADEMY_AI_MAX_TOKENS', '1500'))
ACADEMY_AI_MAX_TOOL_ROUNDS = int(os.environ.get('ACADEMY_AI_MAX_TOOL_ROUNDS', '6'))

# --- AI tutor maintenance switch -------------------------------------------
# The conversational e-learning tutor is being reworked, so it's taken offline
# while that happens. The AI database search is unaffected. Flip this back to
# 'False' in the environment (no code change / redeploy of code needed) to bring
# the tutor back once the rework lands.
AI_TUTOR_OFFLINE = os.environ.get('AI_TUTOR_OFFLINE', 'True') == 'True'
AI_TUTOR_OFFLINE_MESSAGE = os.environ.get(
    'AI_TUTOR_OFFLINE_MESSAGE',
    "Our AI tutor is temporarily offline while we give it a substantial "
    "rework to make it better. It'll be back soon — thanks for your patience."
)

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment in production (set SECRET_KEY in Render).
#
# The fallback below is a placeholder, NOT a real key — there is no secret in
# this file. (An older comment here claimed it was "the existing (un-rotated)
# key", which was never true and would have had the next reader treating it as a
# leak.) The live key was rotated on 2026-08-01, so the value in git history is
# dead too — see AUDIT.md §4.
#
# The fallback stays — owner's decision, 4 Aug 2026, and the question is closed.
# A deploy that lost the env var boots on this known string rather than refusing
# to start; failing loudly would close that and take the site down whenever the
# variable went missing, which is the worse trade for a site one person deploys.
# Don't reopen it as a finding.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-dev-only-key-not-used-in-production',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Env-driven: set DEBUG=False in Render (production). Defaults to True so local
# `runserver` keeps serving static/media without extra flags. See AUDIT.md §4.
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['onlygoodantibodies.com', 'only-good-antibodies.onrender.com', '127.0.0.1', 'oga-website.onrender.com', 'onlygoodantibodies.co.uk',
    'www.onlygoodantibodies.co.uk','localhost',]
CSRF_TRUSTED_ORIGINS = ['https://onlygoodantibodies.co.uk', 'https://www.onlygoodantibodies.co.uk']

# Request body size for large bulk uploads/commits.
# Django reads the JSON body (json.loads(request.body)) on the bulk import/commit
# endpoints, and reading request.body is capped by DATA_UPLOAD_MAX_MEMORY_SIZE.
# The 2.5 MB default forced large batches to be split into smaller files — raise
# it so a whole-dataset commit fits in one request. The full dataset is ~4.8 MB,
# so 10 MB gives ~2x headroom without holding a large body in memory. (Uploaded
# FILES are already exempt from this limit; this only affects the JSON-body path.)
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'django.contrib.humanize',
    'core',
    'django_extensions',
    'academy',
    'pipeline',
    'credentials',
    'selector',
    'crispy_forms',
    'crispy_bootstrap5',
    'allauth', 'allauth.account', 'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'grappelli',                              
    'ckeditor',
    'ckeditor_uploader',
]

MIDDLEWARE = [
    # FIRST, and it has to be. This answers Render's health check, and a health
    # check that cannot pass does not slow a deploy down — it hangs it, leaving
    # the site on the old code with nothing on any screen saying why. Above
    # SecurityMiddleware so an internal probe over plain HTTP can never be
    # answered with a redirect; it validates no host and opens no database.
    # See OGA_website/health.py for what it deliberately does not check.
    'OGA_website.health.HealthCheckMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Public HTML goes out compressed. A gene page is 40-100 KB of markup and
    # Render's router does not compress it, so every crawler that walked the 585
    # gene pages was paying full price for each one. Text at this shape
    # compresses about 5:1.
    #
    # Cloudflare IS in front of this origin and does compress on its way to a
    # visitor -- which is why this looked unnecessary and is not. What Render
    # bills is the ORIGIN-to-Cloudflare hop, and that one was uncompressed:
    # Cloudflare asks for gzip and, until this was added, got 100 KB of markup
    # and compressed it itself, after the bytes had already been paid for.
    #
    # It must sit above WhiteNoise, which serves static files from its own
    # pre-compressed copies and sets Content-Encoding itself; a response that
    # already carries that header is left alone here, so static is not touched
    # twice. The BREACH caveat in Django's own docs is noted and accepted: it
    # needs a secret reflected in the body beside attacker-controlled input, and
    # Django masks the CSRF token per response for exactly this reason. Almost
    # everything compressed here is the anonymous public site.
    'django.middleware.gzip.GZipMiddleware',
    # "You already have this one." A fingerprint of each reply, so a cache that
    # asks whether its copy is still good is answered with 304 and no body at
    # all. Django sets no ETag on its own, so nothing on this site could answer
    # that question and every revalidation cost the full page.
    #
    # It is what makes the extension's two downloads nearly free between
    # releases: `index.json` is ~1 MB and `citations.json` 741 KB gzipped, both
    # fetched daily by every install, against data that changes monthly at most.
    # Cloudflare holds them (a Cache Rule on `/extension/*.json`, see the note
    # in CLAUDE.md) and revalidates with `If-None-Match` when its copy goes
    # stale; with a fingerprint to compare, that revalidation costs bytes rather
    # than megabytes.
    #
    # Placement is both neighbours at once. BELOW GZip, so the ETag is stamped
    # on the uncompressed body and GZip then marks that value *weak* -- which is
    # how Django keeps the two consistent (it appended `;gzip` before 4.1), and
    # the wrong way round would fingerprint bytes that already carry a
    # Content-Encoding. Checked against a gzip client, which is what Cloudflare
    # is: `W/"..."`, and the revalidation still answers 304. ABOVE
    # PublicCacheHeaders, so that middleware has already stamped `Cache-Control`
    # by the time a 304 is built from the reply: Django copies that header onto
    # the 304 (RFC 7232 s4.1), and a revalidation answered without it would
    # leave the edge nothing to re-derive its freshness from.
    'django.middleware.http.ConditionalGetMiddleware',
    # How long a cache may keep a public page. Django sends no Cache-Control at
    # all, and Cloudflare -- which is already in front of this origin -- does
    # not cache HTML it was told nothing about; on 20 Aug 2026 it was serving
    # 15% of the day's bytes and Render the other 85%. The refusals, and the
    # one thing this knowingly accepts, are in OGA_website/cache_headers.py.
    #
    # Above WhiteNoise and below GZip so its RESPONSE phase runs last of the
    # three: it sees the final reply, including a `Set-Cookie` that
    # SessionMiddleware or the CSRF middleware added on the way out, which is
    # what it refuses on.
    'OGA_website.cache_headers.PublicCacheHeadersMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'OGA_website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / "templates",
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                # scope_note / consensus_protocol_url: what a recommendation
                # does and does not cover, for the six surfaces that draw one.
                # See core/context_processors.py for why this is not passed
                # per view.
                'core.context_processors.recommendation_scope',
                # nav_gene: the gene the page is about, so the Browse menu can
                # carry it. See pipeline/context_processors.py for why this is
                # not a template expression.
                'pipeline.context_processors.nav_gene',
                # nav_extension_preview: whether the extension install page is
                # still team-only, so Browse can offer it while it is.
                'pipeline.context_processors.nav_chrome',
                # pipeline_chrome / pipeline_next: whether an account page was
                # reached from the pipeline, so it can wear the pipeline's top
                # bar instead of the public site's. See the docstring.
                'pipeline.context_processors.account_chrome',
                # pipeline_stylesheet: the built stylesheet's URL, or None when
                # it has not been built and the CDN is standing in. See
                # pipeline/styling.py.
                'pipeline.context_processors.stylesheet',
            ],
        },
    },
]

WSGI_APPLICATION = 'OGA_website.wsgi.application'


# ──────────────────────────────────────────────────────────────
# Two databases, split by subject: the science and the people
# ──────────────────────────────────────────────────────────────
#
# pipeline_db (PostgreSQL) — antibody and scientific data. Contains:
#     All YCharOS pipeline models (targets, antibodies, cell lines, sessions,
#     results, figures, reports)
#     Set PIPELINE_DATABASE_URL env var on Render.
#     Falls back to local SQLite for development.
#
# academy_db (PostgreSQL) — people and organisations. Contains:
#     Users, auth, sessions, allauth, all Academy models, credentials,
#     selector, and core's APIConsumer / ReviewedAntibody / ApiUsageDay
#     Set ACADEMY_DATABASE_URL; falls back to the SQLite file. See below.
#
# default — DELIBERATELY EMPTY. There is no third database. Django treats
#     `{}` as "not configured", so any model that reaches `default` raises
#     ImproperlyConfigured at the point of the query instead of quietly
#     reading or writing somewhere plausible. Nothing is routed there:
#     db_router sends pipeline models to pipeline_db and everything else to
#     academy_db, with no branch in between.
#
#     It used to be `db_core.sqlite3` — a SQLite file committed to git holding
#     the retired `core` models (Gene, Antibody, Description, Experiment,
#     CellLine) plus stale copies of the academy tables from before the
#     PostgreSQL move. File and models both went on 23 Aug 2026. Pointing
#     `default` at either live database instead was considered and rejected:
#     `manage.py changepassword` defaults to `--database=default`, and both
#     candidates carry their own `auth_user`, so the documented ghost-write
#     would have become a real one — the wrong person's password changed, and
#     "changed successfully" printed over it.
#
# See OGA_website/db_router.py for the routing logic.
# ──────────────────────────────────────────────────────────────

if os.path.exists('/var/data/'):
    # Render production: academy database on persistent disk (survives deploys)
    ACADEMY_DB_PATH = '/var/data/db_academy.sqlite3'
else:
    # Codespaces / local dev: academy database alongside core
    ACADEMY_DB_PATH = BASE_DIR / 'db_academy.sqlite3'

# academy_db moves to PostgreSQL by setting ACADEMY_DATABASE_URL and nothing
# else — no code change, no deploy, and clearing the variable puts it straight
# back on the file. The same shape as USE_R2 and for the same reason: the switch
# is the whole of the safety, because it makes the cutover and the rollback the
# same size.
#
# The move is not really about SQLite's write concurrency, which one gunicorn
# worker never reaches. It is about the disk: a Render service with a persistent
# disk cannot deploy without downtime, because the disk detaches from the old
# instance before it attaches to the new one. Measured either side of adding the
# health check on 23 Aug 2026, the gap was 40 seconds both times — that is the
# 502. This file is the only thing that needs the disk, so moving it is what
# lets the disk come off, which is what closes the gap and, incidentally, is what
# allows more than one instance at all.
#
# OGA_website/academy_db.py carries the guard that keeps the fallback above from
# becoming a silently-invented empty database once the disk is gone.
DATABASES = {
    'default': {},
    'academy_db': dj_database_url.config(
        env='ACADEMY_DATABASE_URL',
        default=f'sqlite:///{ACADEMY_DB_PATH}',
    ),
    'pipeline_db': dj_database_url.config(
        env='PIPELINE_DATABASE_URL',
        default=f'sqlite:///{BASE_DIR / "db_pipeline.sqlite3"}',
    ),
}

# Read-only source alias for the move itself: set ACADEMY_SQLITE_URL to the
# SQLite file while academy_db already points at PostgreSQL, and
# `academy_db_copy` / `academy_db_compare` can read both at once. Registered only
# when the variable is set, so outside the migration there is no second alias
# sitting on a path that SQLite would silently create if anything touched it.
if os.environ.get('ACADEMY_SQLITE_URL'):
    DATABASES['academy_sqlite'] = dj_database_url.config(env='ACADEMY_SQLITE_URL')

DATABASE_ROUTERS = ['OGA_website.db_router.OGARouter']


# Test-only settings. Guarded on argv being literally `manage.py test ...`, so
# gunicorn, migrate, shell and every other command are untouched — nothing here
# can reach the deploy.
#
# Two things, both measured on 4 Aug 2026 against a 17-minute suite:
#
# 1. PBKDF2 is deliberately slow (~600k iterations, ~510 ms a hash). That is
#    correct in production and ruinous in tests: `tests_timeouts._member_client`
#    creates two users and logs in, which is ~1.54 s of hashing, and it sits in
#    setUp, so it runs once per test rather than once per class. 621 of 828
#    tests pay it — about 16 of the 17 minutes. The actual test logic is ~4
#    seconds. MD5 here is not a security decision; no password set under test
#    outlives the run.
#
# 2. SQLite's test database defaults to in-memory, which `--keepdb` cannot keep,
#    so all three databases were rebuilt through 44 migrations on every
#    invocation — a fixed ~15 s, paid even to run one test. Pointing TEST NAME
#    at a file makes --keepdb work: a warm single-module run goes 104 s -> 3 s.
#
# Measured together: the full Django suite runs 864 tests in ~20 s.
if sys.argv[1:2] == ['test']:
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']
    # The migration's second alias always exists under test, so `academy_db_copy`
    # can be driven for real between two databases that both carry the academy
    # schema. Preserving every primary key is the property the whole move rests
    # on — a renumbered user is a session pointing at the wrong person — and it
    # is not a property you can check without somewhere to copy to.
    DATABASES.setdefault('academy_sqlite', {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_academy_source.sqlite3',
    })
    # `default` is `{}` and must stay that way — Django decides a database is
    # unconfigured by looking for ENGINE, and a `default` carrying a TEST block
    # is an alias the test runner would try to create.
    #
    # DEPENDENCIES is the half that is not obvious. Django defaults every
    # non-default alias to `TEST['DEPENDENCIES'] = ['default']`, so that the
    # default database is set up first. With `default` empty there is nothing
    # to set up and nothing to depend on, and the runner fails resolving the
    # order — `ImproperlyConfigured: Circular dependency in TEST[DEPENDENCIES]`,
    # which names neither the alias nor `default` and reads like a settings
    # typo. Stating the empty list is the documented answer for a project with
    # no default database.
    for _alias, _config in DATABASES.items():
        if not _config:
            continue
        _config.setdefault('TEST', {})
        _config['TEST']['NAME'] = str(BASE_DIR / f'test_{_alias}.sqlite3')
        _config['TEST']['DEPENDENCIES'] = []


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --- Cache ------------------------------------------------------------------
# There was no CACHES setting at all, so Django's own default applied:
# local-memory, per process. Five things share it — the gene search index, the
# public antibody search index, the extension snapshot, the bulk archive's
# "does it exist yet" check, and the API rate limiter — and each gunicorn worker
# keeps its own copy. For the first four that is only waste: they are pure
# speed, so a cold worker is a slow answer and never a wrong one. For the rate
# limiter it is the ceiling, because there the tally *is* the limit — a consumer
# gets roughly the nominal rate per worker, which is what `core.W003` reports.
#
# Set `CACHE_URL` (or Render's `REDIS_URL`) to a Redis-compatible instance — a
# Render Key Value service — and the same code becomes exact. Nothing else has
# to change; `api_throttle.using_shared_cache()` reads the backend name and
# `core.W003` goes quiet on its own.
#
# **`IGNORE_EXCEPTIONS` is the whole reason for django-redis** rather than
# Django's built-in `RedisCache`, which raises when the instance is unreachable.
# Everything in this project degrades rather than fails — a dead UniProt returns
# `unchecked`, a missing stylesheet falls back to the CDN — and a cache is the
# wrong thing to take a site down for: the gene pages and the search box would
# 500 over an unavailable *optimisation*. The trade is stated rather than
# hidden: with the cache unreachable, `_hit` cannot accumulate, so the API
# throttle fails **open**. That is the right direction for a guard on data that
# is public anyway, and it is why the real ceiling belongs at Cloudflare, which
# sees the connection and cannot be talked out of it.
_cache_url = os.environ.get('CACHE_URL') or os.environ.get('REDIS_URL', '')

if _cache_url:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': _cache_url,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': True,
            },
            'KEY_PREFIX': 'oga',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'oga',
        }
    }


# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'core/static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- Browser extension ------------------------------------------------------
# Announcement switch. While this is False the install page is unlisted: it is
# not linked from the Tools hub and asks search engines not to index it, so the
# code can be deployed with nothing user-visible changing. That is deliberate —
# building the bundled data snapshot needs `manage.py build_extension_index`
# running against the live pipeline database, which means the code has to be on
# the server before the extension can be submitted to the stores.
# Flip to 'True' in the environment once the listings are live (no redeploy).
EXTENSION_PAGE_PUBLIC = os.environ.get('EXTENSION_PAGE_PUBLIC', 'False') == 'True'

# Store listings. Left blank until each store approves. The install page shows
# those buttons as pending rather than linking nowhere. Set these in Render when
# the listings go live — again, no redeploy of code needed.
# Self-distributed Firefox build. Set both once Mozilla returns a signed .xpi
# and it is hosted somewhere Firefox can fetch it; /extension/updates.json then
# starts offering it and installed copies update themselves. Until then the
# update manifest correctly reports "no updates".
EXTENSION_XPI_URL = os.environ.get(
    'EXTENSION_XPI_URL',
    'https://onlygoodantibodies.co.uk/extension/firefox.xpi',
)
EXTENSION_XPI_VERSION = os.environ.get('EXTENSION_XPI_VERSION', '')

EXTENSION_CHROME_URL = os.environ.get('EXTENSION_CHROME_URL', '')
EXTENSION_FIREFOX_URL = os.environ.get('EXTENSION_FIREFOX_URL', '')
EXTENSION_EDGE_URL = os.environ.get('EXTENSION_EDGE_URL', '')

# ── Media storage: local filesystem by default; Cloudflare R2 when USE_R2 ──
# The switch is explicit so this deploys INERT — nothing changes until
# USE_R2=True is set in the environment (only after media is uploaded to R2
# and verified). Static files stay on WhiteNoise, untouched. Object keys keep
# their existing relative paths (e.g. 'experiments/foo.png'), so the database
# needs no changes. Migration completed 2026-07-13; see AUDIT.md §5-6.
USE_R2 = os.environ.get('USE_R2', 'False') == 'True'

# ── Raw session files go somewhere the public route does not reach ──────────
# The media bucket is public by design (the public antibody pages serve
# publication images off it). An uncropped gel scan is unpublished lab data and
# does not belong on the same public route, so `pipeline/storages.py` gives
# `FileAttachment.file` its own storage: no custom domain, signed URLs.
#
# Set R2_ATTACHMENTS_BUCKET to a bucket with NO public access. Left empty, the
# files still store, serve and download correctly — they simply sit in the media
# bucket, reachable on the public domain by anyone who knows the key. A system
# check says so rather than the app refusing to boot over it.
R2_ATTACHMENTS_BUCKET = os.environ.get('R2_ATTACHMENTS_BUCKET', '')
R2_ATTACHMENT_URL_SECONDS = int(os.environ.get('R2_ATTACHMENT_URL_SECONDS', '300'))

# Filesystem paths that survive a Render deploy. Everything else under the
# container's own filesystem is rebuilt from git on every deploy, which is why
# an upload landing there is refused rather than silently lost — see
# `pipeline/services/attachments.py::storage_refusal`.
PERSISTENT_MEDIA_ROOTS = ('/var/data',)

# ── Zenodo ──────────────────────────────────────────────────────────────────
# Empty token = the deposit button is greyed with the reason on the page, and
# the preview still works (it makes no network call), so the whole thing can be
# read and checked before any account exists.
#
# ZENODO_BASE_URL points at sandbox.zenodo.org while this is being commissioned:
# a separate site with its own logins and its own tokens, issuing test DOIs
# under the 10.5072 prefix, so the flow can be driven end to end without one
# real record existing. The scopes the token needs are `deposit:write` AND
# `deposit:actions` — the second is what submits, and without it a draft is
# created and then cannot be handed to the community.
ZENODO_API_TOKEN = os.environ.get('ZENODO_API_TOKEN', '')
ZENODO_BASE_URL = os.environ.get('ZENODO_BASE_URL', 'https://zenodo.org')
ZENODO_COMMUNITY = os.environ.get('ZENODO_COMMUNITY', 'ycharos')

# Static files are served under a content hash, so a deploy cannot be shadowed
# by a copy a browser or an edge cache is already holding — the failure that
# left the gene page's Delete button drawn and dead on 5 Aug 2026. The default
# `default` entry is Django's own and is replaced below when R2 is on.
# `OGA_website/storages.py` carries the reasoning, including why the hashing is
# deliberately non-strict.
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'OGA_website.storages.HashedStaticFilesStorage'},
}

if USE_R2:
    AWS_ACCESS_KEY_ID = os.environ.get('R2_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('R2_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.environ.get('R2_ENDPOINT_URL')
    AWS_S3_REGION_NAME = 'auto'              # R2 ignores region; 'auto' is required
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_DEFAULT_ACL = None                   # R2 has no per-object ACLs
    AWS_QUERYSTRING_AUTH = False             # public URLs, no signed querystrings
    AWS_S3_FILE_OVERWRITE = False            # keep Django's dedup-suffix behaviour
    # Public host that serves the bucket (a Cloudflare custom domain/route),
    # set at flip time. Keys like 'experiments/foo.png' → .url becomes
    # https://<R2_PUBLIC_DOMAIN>/experiments/foo.png
    R2_PUBLIC_DOMAIN = os.environ.get('R2_PUBLIC_DOMAIN')
    AWS_S3_CUSTOM_DOMAIN = R2_PUBLIC_DOMAIN or None

    # Media moves to R2; static files stay on WhiteNoise either way, so only the
    # `default` half changes here.
    STORAGES['default'] = {'BACKEND': 'storages.backends.s3.S3Storage'}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' 
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'onlygoodantibodies@gmail.com'
# Set EMAIL_HOST_PASSWORD in Render. Empty fallback = email disabled (site stays
# up); it does NOT crash the app. Must be set in Render before deploying.
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

####################
## Todo: Fix this ##
####################

# Protect Session and CSRF Cookies
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Enforce Secure Cookies (Only over HTTPS)
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# Restrict Cookie Access to Your Website (Prevents Cross-Site Attacks)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Strict'

# Session Expiry
SESSION_COOKIE_NAME = "sessionid"
SESSION_COOKIE_AGE = 28800          # 8 hours
SESSION_SAVE_EVERY_REQUEST = True   # Resets the timer on every page load
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Redirects
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = 'academy:academy_home'

# Crispy Forms (Bootstrap 5)
CRISPY_ALLOWED_TEMPLATE_PACKS = ['bootstrap5']
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# django-allauth
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'optional'

# Social Login Providers
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '<your-google-client-id>',
            'secret': '<your-google-secret>',
            'key': ''
        }
    }
}

ACCOUNT_FORMS = {
    'signup': 'academy.forms.CustomSignupForm',
    # Labels the sign-in field with what to type in it. allauth calls it "Login"
    # when both username and email are accepted; see academy/forms.py.
    'login': 'academy.forms.CustomLoginForm',
}

# reCAPTCHA v3
RECAPTCHA_SITE_KEY = '6Le5xYQsAAAAANvEjeuuSWJ8jNsev7H-WPNAt4ht'
RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY', '')

CKEDITOR_UPLOAD_PATH = "lesson_uploads/"
CKEDITOR_CONFIGS = {
  'default': {
    'toolbar': 'full',
    'height': 300,
    'width': '100%',
  },
}